[phases.setup]
nixPkgs = ["nodejs_20", "nss", "atk", "cups", "alsa-lib", "pango", "gtk3", "xorg.libxshmfence", "xorg.libXScrnSaver", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXrandr", "libdrm", "mesa"]

[start]
cmd = "node server.js"
